package com.example.expensetracker.model;

public enum Category {
    HOUSING, TRANSPORTATION, FOOD, UTILITIES, CLOTHING, HEALTHCARE, INSURANCE, HOUSEHOLD_SUPPLIES, PERSONAL,
    DEBT, RETIREMENT, EDUCATION, SAVINGS, GIFTS, ENTERTAINMENT
}
